name: Sphinx Documentation

on:
  push:
    branches:    
      - main

jobs:
  build:


    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
      with: # for github push action
        #persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install documentation dependencies
      run: |
        pip install sphinx numpydoc matplotlib     
    - name: Setup cmake
      run: |
        ls 
        cd src
        cmake ./src/ -G"Visual Studio 16 2019" -DCMAKE_GENERATOR_PLATFORM="x64"  -DCMAKE_CONFIGURATION_TYPES="Debug" -DCMAKE_INSTALL_PREFIX=".\..\build\Python" -DHumanFactors_Config="All" -DHumanFactors_EnableTests="False" -DCMAKE_BUILD_TYPE="Debug" -DHumanFactors_EnablePython="True" -DHumanFactors_EnableCSharp="False" -DINSTALL_GTEST="False"  ".\" 2>&1 
    - name: cmake build
      run: |
        cmake --build ../src
    - name: cmake Install
      run: |
        cmake --install .
    - name: Install package
      run: |
        cd ../build/Python
        pip install -e .
    - name: Install Sphinx Latex
      run: |
        sudo apt-get update -y && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
    - name: Build documentation with sphinx
      run: |
        cd docs
        make clean
        make html
        make latexpdf
        ls

    - name: Auto-deploy doc changes
      run : |

        git config --local user.email "action@github.com"
        git config --local user.name "github-actions[bot]"

        mkdir html_build
        git worktree add -B docs html_build origin/docs

        cp -a docs/. html_build/

        cd html_build

        git add . 
        git commit -m "ghpages for python docs"
        git push 
            
